source :rubygems

# PostgreSQL driver
gem 'pg'

# Sinatra driver
gem 'sinatra'
gem 'sinatra-contrib'

# Use Thin for our web server
gem 'thin'

gem 'activesupport'
gem 'activerecord'

gem 'rake'

gem 'shotgun'

group :development do
  gem 'guard-rspec'
end

group :test do
  gem 'faker'
  gem 'rspec'
  gem 'simplecov'
end
